/**

 * Premium Code Generator — GlimpZ Project

 * Author: Aman

 * Generates redeemable premium codes.

 */

const { EmbedBuilder } = require("discord.js");

const fs = require("fs");

const path = require("path");

const crypto = require("crypto");

const { loadData, savePremiumData, parseDuration } = require("../utils/premiumManager");

const owners = ["1113808268960206928", "832640702802296882"]; // Replace with your Discord IDs

const dataPath = path.join(__dirname, "../data/premiumData.json");

module.exports = {

  name: "pgen",

  description: "Generate a premium code for a tier and duration.",

  usage: "!pgen <tier> <duration>",

  cooldown: 3,

  async execute(message, args) {

    try {

      if (!owners.includes(message.author.id)) {

        return message.reply({

          embeds: [

            new EmbedBuilder()

              .setColor("#ff4444")

              .setTitle("⛔ Access Denied")

              .setDescription("Only bot owners can generate premium codes.")

              .setFooter({ text: "Premium Manager System" }),

          ],

        });

      }

      if (!args[0] || !args[1]) {

        return message.reply({

          embeds: [

            new EmbedBuilder()

              .setColor("#ffcc00")

              .setTitle("⚠️ Invalid Usage")

              .setDescription(

                "**Usage:** `!pgen <tier> <duration>`\n\n**Examples:**\n`!pgen gold 1month`\n`!pgen silver 3months`\n`!pgen platinum lifetime`"

              )

              .setFooter({ text: "Premium Manager System" }),

          ],

        });

      }

      const tier = args[0].toLowerCase();

      const validTiers = ["bronze", "silver", "gold", "platinum"];

      if (!validTiers.includes(tier)) {

        return message.reply({

          embeds: [

            new EmbedBuilder()

              .setColor("#ffcc00")

              .setTitle("⚠️ Invalid Tier")

              .setDescription("Valid tiers are: `bronze`, `silver`, `gold`, `platinum`.")

              .setFooter({ text: "Premium Manager System" }),

          ],

        });

      }

      const duration = parseDuration(args[1]);

      if (!duration) {

        return message.reply({

          embeds: [

            new EmbedBuilder()

              .setColor("#ffcc00")

              .setTitle("⚠️ Invalid Duration")

              .setDescription("Use valid durations like `1w`, `1month`, `3months`, `1y`, or `lifetime`.")

              .setFooter({ text: "Premium Manager System" }),

          ],

        });

      }

      // 🧩 Load data safely

      const data = loadData();

      // 🛠️ Ensure data.codes exists

      if (!data.codes) data.codes = [];

      // 🎟️ Generate unique code

      const code = crypto.randomBytes(4).toString("hex").toUpperCase().slice(0, 7);

      data.codes.push({

        code,

        tier: tier.charAt(0).toUpperCase() + tier.slice(1),

        duration,

        createdBy: message.author.id,

        createdAt: Date.now(),

        expires: Date.now() + duration,

      });

      savePremiumData(data);

      // ✅ Success Embed

      const embed = new EmbedBuilder()

        .setColor("#00ff99")

        .setTitle("🎟️ Premium Code Generated")

        .setDescription(

          `**💎 Tier:** ${tier.charAt(0).toUpperCase() + tier.slice(1)}\n` +

          `**🕒 Duration:** ${args[1]}\n` +

          `**🔢 Code:** \`${code}\`\n\nUse this code with \`!premium-activate <code>\``

        )

        .setFooter({ text: `Generated by ${message.author.tag}` })

        .setTimestamp();

      return message.reply({ embeds: [embed] });

    } catch (err) {

      console.error("Error in pgen.js:", err);

      return message.reply({

        embeds: [

          new EmbedBuilder()

            .setColor("#ff0000")

            .setTitle("❌ Error Generating Code")

            .setDescription("An unexpected error occurred while generating the premium code.")

            .setFooter({ text: "Premium Manager System" }),

        ],

      });

    }

  },

};